
services:
  presentation:
    image: veroyols/presentation:deploy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80:80"
    depends_on:
      - bioc
      - blast
      - biopython 
  
  bioc:
    image: veroyols/bioc:deploy
    ports:
      - "8000:8000"

  blast:
    image: veroyols/blast:deploy
    ports:
      - "8001:8001"

  biopython:
    image: veroyols/biopython:deploy
    ports:
      - "8002:8002"  